### ISSUE TITLE
Did it break?

### ISSUE THREAD

**Issue by xxshady** [zziger/altv-powertoys-run-natives#1]
![изображение](https://user-images.githubusercontent.com/54737754/208537469-44fe2aaf-58f7-41e3-a193-9d597edc8415.png)

Nothing is displayed when entering native name

![изображение](https://user-images.githubusercontent.com/54737754/208537563-8c304f3e-440d-4f38-84ff-b29ad3638442.png)

Plugin location:
`G:\program files\PowerToys\modules\launcher\Plugins\AltVNatives`

File structure:

![изображение](https://user-images.githubusercontent.com/54737754/208537997-c1ccc6cb-ea90-4bb1-addc-95fcbc5e028b.png)

Full plugin folder content:

![изображение](https://user-images.githubusercontent.com/54737754/208538155-cc42eb66-f545-4cb1-b7b7-21a703eeca05.png)

**Comment by zziger** [comment]
I'll check tonight, thx

**Comment by zziger** [comment]
Fixed in release 1.2.0

**Comment by xxshady** [comment]
![ezgif-2-0df9387d89](https://user-images.githubusercontent.com/54737754/209188918-0cce1e2c-7a09-44ce-b9f5-1e0346aa2ad7.gif)
